# Site Settings
name: TheMana
title: TheMana | Force From Within
description: La forza del cambiamento arriva da dentro
tags:
  - themana
  - mana
  - blog
  - tecnologia
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: youremail@test.com
disqus_username: disqus_username


# Social Media Settings
# Remove the item if you don't need it
github_username: mana-it
facebook_username: facebook_username
twitter_username: twitter_username
instagram_username: themana_it
linkedin_username: themana
medium_username: medium_username


# Posts Settings
show_time_bar: true
show_modal_on_exit: false
show_modal_on_finish_post: true
two_columns_layout: true


# Translations Settings
translations:
  texts:
    new_post: Nuovo Post
    seel_also: Vedi anche
    search: Cerca
    author: Autore
    share: Condividi
    comments: Commenti
  button:
    read_now: Leggi ora
    share_on_twitter: Condividi su Twitter
    share_on_facebook: Condividi su Facebook
  pagination:
    page: Pagina
    of: di
    next_page: Prossima Pagina
    next_post: Prossimo Post
  recommendation:
    text: Perché non leggi qualcos'altro?
    back_btn: Torna su
  error_404:
    title: Pagina non trovata :(
    message: Ci dispiace, ma non riusciamo a trovare la pagina che stai cercando.
      Assumeremo subito un investigatore privato per cercare di ritrovarla.
    image_alt: 404 - Pagina non trovata
  contact:
    placeholders:
      name: Il tuo Nome
      email: La tua email
      message: Il tuo messaggio
    errors:
      locale: it
      empty_name: inserisci il tuo nome
      empty_email: inserisci la tua email
      invalid_email: email non valida
      empty_message: inserisci il tuo messaggio
    after_send:
      title: Messaggio inviato!
      message: Grazie per averci contattato :)
    title: Parla con noi!
    subject: Ciao!
    submit_btn: Invia
texts:
  new_post: Nuovo Post
  seel_also: Vedi Anche
  search: Cerca
  share: Condividi
  comments: Commenti
button:
  read_now: Leggi ora
  share_on_twitter: Condividi su Twitter
  share_on_facebook: Condividi su Facebook
pagination:
  page: Pagina
  of: di
  next_page: Prossima Pagina
  next_post: Prossimo Post
recommendation:
  text: Potrebbero interessarti anche questi articoli
  back_btn: Torna su
error_404:
  title: Pagina non trovata :(
  message: Ci dispiace, ma non riusciamo a trovare la pagina che stai cercando.
    Assumeremo subito un investigatore privato per cercare di ritrovarla.
  image_alt: 404 - Pagina non trovata
contact:
  placeholders:
    name: Il tuo nome
    email: La tua email
    message: Il tuo messaggio
  errors:
    locale: it
    empty_name: inserisci il tuo nome
    empty_email: inserisci la tua email
    invalid_email: email non valida
    empty_message: inserisci il tuo messaggio
  title: Contattaci
  subject: Ciao!
  submit_btn: Invia
  after_send:
    title: Messaggio inviato!
    message: Grazie per averci contattato, ti risponderemo il prima possibile


# Advanced Settings
baseurl: ""
url: ""
google_analytics: UA-XXXXXXXX-X
language: it
categories_folder: category
sent_message_url: /contact/message-sent/


# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
collections:
  authors:
    output: true
paginate_path: "/page/:num/"
show_get_theme_btn: true
get_theme_btn_text: Gruppo Telegram
get_theme_btn_link: "https://t.me/TheMana_it_group"
use_logo: false

# Content paginator
paginate_content:
  enabled: true
  debug: false
  collections:
    - posts
  auto: false
  separator: "--page-break--"
  permalink: "/:num/"
  seo_canonical: true
  properties:
    part:
      is_generated: true
    last:
      is_generated: true
    single:
      is_generated: true

# SASS
sass:
  style: compressed

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-paginate-content

# Exclude my node related stuff
exclude: [
  'package.json',
  'package-lock.json',
  'src',
  'node_modules',
  'initpost.sh',
  'Gemfile',
  'Gemfile.lock',
  'gulpfile.js',
  'README.md'
]

# Theme
version: v0.1.0
