name: TheMana
title: TheMana | Force From Within
description: Jekflix is a template for Jekyll inspired by Netflix and made by
  Thiago Rossener.
tags:
  - themana
  - mana
  - blog
  - tecnologia
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: youremail@test.com
disqus_username: disqus_username
